export const SPORTS_BY_CATEGORY = [
  {
    label: 'CARDIO & ENDURANCE',
    sports: [
      { slug: 'running', label: 'Running', emoji: '🏃' },
      { slug: 'trail', label: 'Trail', emoji: '🥾' },
      { slug: 'marche', label: 'Marche', emoji: '🚶' },
      { slug: 'randonnee', label: 'Randonnée', emoji: '🥾' },
      { slug: 'cyclisme', label: 'Cyclisme', emoji: '🚴' },
      { slug: 'vtt', label: 'VTT', emoji: '🚵' },
      { slug: 'triathlon', label: 'Triathlon', emoji: '🏇' },
      { slug: 'aviron', label: 'Aviron', emoji: '🛶' },
      { slug: 'duathlon', label: 'Duathlon', emoji: '🏃' },
      { slug: 'course-orientation', label: "Course d'orientation", emoji: '🧭' },
    ],
  },
  {
    label: 'ATHLÉTISME',
    sports: [
      { slug: 'sprint', label: 'Sprint', emoji: '💨' },
      { slug: 'demi-fond', label: 'Demi-fond', emoji: '🏃' },
      { slug: 'marathon', label: 'Marathon', emoji: '🏃' },
      { slug: 'haies', label: 'Haies', emoji: '🏃' },
      { slug: 'saut-longueur', label: 'Saut en longueur', emoji: '🤸' },
      { slug: 'saut-hauteur', label: 'Saut en hauteur', emoji: '🤸' },
      { slug: 'saut-perche', label: 'Saut à la perche', emoji: '🤸' },
      { slug: 'lancer-disque', label: 'Lancer du disque', emoji: '🥏' },
      { slug: 'lancer-javelot', label: 'Lancer du javelot', emoji: '🏹' },
      { slug: 'decathlon', label: 'Décathlon', emoji: '💪' },
    ],
  },
  {
    label: 'FORCE & FITNESS',
    sports: [
      { slug: 'musculation', label: 'Musculation', emoji: '🏋️' },
      { slug: 'crossfit', label: 'CrossFit', emoji: '🔥' },
      { slug: 'hiit', label: 'HIIT', emoji: '⚡' },
      { slug: 'fitness', label: 'Fitness', emoji: '🤸' },
      { slug: 'yoga', label: 'Yoga', emoji: '🧘' },
      { slug: 'pilates', label: 'Pilates', emoji: '🩰' },
      { slug: 'halterophilie', label: 'Haltérophilie', emoji: '🏅' },
      { slug: 'gymnastique', label: 'Gymnastique', emoji: '🤸' },
      { slug: 'calisthenics', label: 'Calisthenics', emoji: '💪' },
      { slug: 'stretching', label: 'Stretching', emoji: '🌀' },
      { slug: 'aerobic', label: 'Aérobic', emoji: '🤸' },
    ],
  },
  {
    label: 'SPORTS COLLECTIFS',
    sports: [
      { slug: 'football', label: 'Football', emoji: '⚽' },
      { slug: 'futsal', label: 'Futsal', emoji: '🥅' },
      { slug: 'basketball', label: 'Basketball', emoji: '🏀' },
      { slug: 'handball', label: 'Handball', emoji: '🤾' },
      { slug: 'volleyball', label: 'Volleyball', emoji: '🏐' },
      { slug: 'rugby', label: 'Rugby', emoji: '🏉' },
      { slug: 'hockey', label: 'Hockey', emoji: '🏑' },
      { slug: 'ultimate', label: 'Ultimate Frisbee', emoji: '🥏' },
      { slug: 'football-americain', label: 'Football américain', emoji: '🏈' },
      { slug: 'beach-volley', label: 'Beach volley', emoji: '🏐' },
      { slug: 'water-polo', label: 'Water-polo', emoji: '🤽' },
    ],
  },
  {
    label: 'RAQUETTE & PRÉCISION',
    sports: [
      { slug: 'tennis', label: 'Tennis', emoji: '🎾' },
      { slug: 'badminton', label: 'Badminton', emoji: '🏸' },
      { slug: 'tennis-table', label: 'Tennis de table', emoji: '🏓' },
      { slug: 'padel', label: 'Padel', emoji: '🎯' },
      { slug: 'squash', label: 'Squash', emoji: '🎱' },
      { slug: 'golf', label: 'Golf', emoji: '⛳' },
      { slug: 'tir-arc', label: "Tir à l'arc", emoji: '🎯' },
      { slug: 'petanque', label: 'Pétanque', emoji: '🎳' },
      { slug: 'billard', label: 'Billard', emoji: '🎱' },
      { slug: 'flechettes', label: 'Fléchettes', emoji: '🏹' },
    ],
  },
  {
    label: 'COMBAT & ARTS MARTIAUX',
    sports: [
      { slug: 'boxe', label: 'Boxe', emoji: '🥊' },
      { slug: 'judo', label: 'Judo', emoji: '🥋' },
      { slug: 'karate', label: 'Karaté', emoji: '🥋' },
      { slug: 'taekwondo', label: 'Taekwondo', emoji: '🥋' },
      { slug: 'mma', label: 'MMA', emoji: '🥋' },
      { slug: 'kick-boxing', label: 'Kick-boxing', emoji: '🥋' },
      { slug: 'lutte', label: 'Lutte', emoji: '🤼' },
      { slug: 'escrime', label: 'Escrime', emoji: '⚔️' },
      { slug: 'krav-maga', label: 'Krav-maga', emoji: '🥋' },
      { slug: 'ju-jitsu', label: 'Ju-jitsu', emoji: '🥋' },
      { slug: 'capoeira', label: 'Capoeira', emoji: '🥋' },
      { slug: 'aikido', label: 'Aïkido', emoji: '🥋' },
      { slug: 'savate', label: 'Savate', emoji: '🥋' },
      { slug: 'muay-thai', label: 'Muay-thaï', emoji: '🥋' },
    ],
  },
  {
    label: 'AQUATIQUE & NAUTIQUE',
    sports: [
      { slug: 'natation', label: 'Natation', emoji: '🏊' },
      { slug: 'aquagym', label: 'Aquagym', emoji: '🏊' },
      { slug: 'surf', label: 'Surf', emoji: '🏄' },
      { slug: 'kayak', label: 'Kayak', emoji: '🚣' },
      { slug: 'paddle', label: 'Paddle SUP', emoji: '🏄' },
      { slug: 'plongee', label: 'Plongée', emoji: '🤿' },
      { slug: 'voile', label: 'Voile', emoji: '⛵' },
      { slug: 'canoe', label: 'Canoë', emoji: '🚣' },
      { slug: 'natation-sync', label: 'Natation synchronisée', emoji: '🏊' },
      { slug: 'wakeboard', label: 'Wakeboard', emoji: '🏄' },
      { slug: 'apnee', label: 'Apnée', emoji: '🤿' },
      { slug: 'rafting', label: 'Rafting', emoji: '🚣' },
    ],
  },
  {
    label: 'GLISSE, MONTAGNE & URBAIN',
    sports: [
      { slug: 'ski-alpin', label: 'Ski alpin', emoji: '⛷️' },
      { slug: 'ski-nordique', label: 'Ski nordique', emoji: '🎿' },
      { slug: 'snowboard', label: 'Snowboard', emoji: '🏂' },
      { slug: 'escalade', label: 'Escalade', emoji: '🧗' },
      { slug: 'skate', label: 'Skate', emoji: '🛹' },
      { slug: 'bmx', label: 'BMX', emoji: '🚵' },
      { slug: 'trottinette', label: 'Trottinette freestyle', emoji: '🛴' },
      { slug: 'parkour', label: 'Parkour', emoji: '🏃' },
      { slug: 'alpinisme', label: 'Alpinisme', emoji: '🧗' },
      { slug: 'ski-rando', label: 'Ski de randonnée', emoji: '🏔️' },
      { slug: 'roller', label: 'Roller', emoji: '🛼' },
      { slug: 'patinage', label: 'Patinage', emoji: '🧊' },
    ],
  },
  {
    label: 'BIEN-ÊTRE, DANSE & DIVERS',
    sports: [
      { slug: 'danse', label: 'Danse', emoji: '💃' },
      { slug: 'hip-hop', label: 'Hip-hop', emoji: '🎭' },
      { slug: 'zumba', label: 'Zumba', emoji: '💃' },
      { slug: 'equitation', label: 'Équitation', emoji: '🐎' },
      { slug: 'cirque', label: 'Cirque', emoji: '🎪' },
      { slug: 'qi-gong', label: 'Qi Gong', emoji: '🧘' },
      { slug: 'tai-chi', label: 'Taï-chi', emoji: '🧘' },
      { slug: 'danse-sportive', label: 'Danse sportive', emoji: '🛼' },
      { slug: 'cheerleading', label: 'Cheerleading', emoji: '📣' },
      { slug: 'tir-sportif', label: 'Tir sportif', emoji: '🏹' },
      { slug: 'parachutisme', label: 'Parachutisme', emoji: '🪂' },
      { slug: 'parapente', label: 'Parapente', emoji: '🪂' },
    ],
  },
];

export function getSportBySlug(slug) {
  for (const category of SPORTS_BY_CATEGORY) {
    const sport = category.sports.find((s) => s.slug === slug);
    if (sport) return sport;
  }
  return null;
}
